//
// Created by NigelWork on 22/04/2024.
//

#ifndef OPENGLCOURSEWORK_OPENGLBUFFERMANAGER_H
#define OPENGLCOURSEWORK_OPENGLBUFFERMANAGER_H


class openGLBufferManager {

};


#endif //OPENGLCOURSEWORK_OPENGLBUFFERMANAGER_H
